# Configuracoes de conexao com o banco H2 (em memoria)
spring.datasource.url=jdbc:h2:mem:stratega
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=
spring.datasource.password=

# Pede para o JPA recriar as tabelas toda vez que o programa rodar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o console do banco no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console